# Generated by Django 6.0.3 on 2026-04-17 17:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='मंजुरी स्थिती')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'मंजुरी स्थिती',
                'verbose_name_plural': 'मंजुरी स्थिती',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetentAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='सक्षम प्राधिकारी')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'सक्षम प्राधिकारी',
                'verbose_name_plural': 'सक्षम प्राधिकारी',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='दस्तऐवज प्रकार')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'दस्तऐवज प्रकार',
                'verbose_name_plural': 'दस्तऐवज प्रकार',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='गट/सर्व्हे नंबर')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'गट/सर्व्हे',
                'verbose_name_plural': 'गट/सर्व्हे',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True, verbose_name='तपासणी वर्ष')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'तपासणी वर्ष',
                'verbose_name_plural': 'तपासणी वर्षे',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LitigationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='न्यायप्रविष्ट स्थिती')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'न्यायप्रविष्ट स्थिती',
                'verbose_name_plural': 'न्यायप्रविष्ट स्थिती',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='कार्यालयाचे नाव')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'कार्यालय',
                'verbose_name_plural': 'कार्यालये',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='मालमत्ता प्रकार')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'मालमत्ता प्रकार',
                'verbose_name_plural': 'मालमत्ता प्रकार',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='शेरा')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'शेरा',
                'verbose_name_plural': 'शेरे',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='तालुका')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'तालुका',
                'verbose_name_plural': 'तालुके',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='एकक')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'एकक',
                'verbose_name_plural': 'एकके',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('AG', 'मा. महालेखापाल'), ('IG', 'मा. नोंदणी महानिरीक्षक'), ('DIG', 'मा. नोंदणी उपमहानिरीक्षक'), ('SDO', 'सहजिल्हा निबंधक'), ('URGENT', 'तात्काळ तपासणी'), ('SPECIAL', 'विशेष तपासणी'), ('OTHER', 'इतर तपासणी')], max_length=10, verbose_name='तपासणी प्रकार')),
                ('sr_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='अनुक्रमांक')),
                ('deed_number', models.CharField(max_length=50, verbose_name='दस्त क्रमांक')),
                ('execution_date', models.DateField(verbose_name='निष्पादन दिनांक')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='नोंदणी दिनांक')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='क्षेत्रफळ')),
                ('village', models.CharField(blank=True, default='', max_length=255, verbose_name='गाव/मौजे')),
                ('executant_name', models.CharField(blank=True, default='', max_length=500, verbose_name='निष्पादकाचे नाव')),
                ('claimant_name', models.CharField(blank=True, default='', max_length=500, verbose_name='दावेदाराचे नाव')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='बाजार मूल्य')),
                ('consideration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='मोबदला रक्कम')),
                ('higher_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='जास्त रक्कम (मूल्यांकन)')),
                ('stamp_duty_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='वसूल केलेला मुद्रांक शुल्क')),
                ('stamp_duty_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='आवश्यक मुद्रांक शुल्क')),
                ('stamp_duty_short', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='कमी पडलेला मुद्रांक शुल्क')),
                ('reg_fee_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='वसूल केलेली नोंदणी फी')),
                ('reg_fee_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='आवश्यक नोंदणी फी')),
                ('reg_fee_short', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='कमी पडलेली नोंदणी फी')),
                ('total_short', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='एकुण कमी')),
                ('total_months', models.PositiveIntegerField(default=0, verbose_name='एकुण महिने')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='शास्ती रक्कम')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='एकुण रक्कम')),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='वसूल रक्कम')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='शिल्लक रक्कम')),
                ('recovery_date', models.DateField(blank=True, null=True, verbose_name='वसुली दिनांक')),
                ('challan_number', models.CharField(blank=True, default='', max_length=100, verbose_name='चलन क्रमांक')),
                ('additional_remark', models.TextField(blank=True, default='', verbose_name='अतिरिक्त शेरा')),
                ('memo_number', models.CharField(blank=True, default='', max_length=100, verbose_name='मेमो क्रमांक')),
                ('memo_date', models.DateField(blank=True, null=True, verbose_name='मेमो दिनांक')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='तपासणी दिनांक')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.approvalstatus', verbose_name='मंजुरी स्थिती')),
                ('competent_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.competentauthority', verbose_name='सक्षम प्राधिकारी')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.documenttype', verbose_name='दस्तऐवज प्रकार')),
                ('group_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.groupsurvey', verbose_name='गट/सर्व्हे')),
                ('inspection_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.inspectionyear', verbose_name='तपासणी वर्ष')),
                ('litigation_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.litigationstatus', verbose_name='न्यायप्रविष्ट स्थिती')),
                ('office_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.officename', verbose_name='कार्यालयाचे नाव')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.propertytype', verbose_name='मालमत्ता प्रकार')),
                ('remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.remark', verbose_name='शेरा')),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection.taluka', verbose_name='तालुका')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.unit', verbose_name='एकक')),
            ],
            options={
                'verbose_name': 'तपासणी मेमो',
                'verbose_name_plural': 'तपासणी मेमो',
                'ordering': ['-created_at'],
            },
        ),
    ]
