# Generated by Django 6.0.3 on 2026-04-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, verbose_name='कार्यालयाचे नांव')),
                ('office_address', models.TextField(blank=True, null=True, verbose_name='कार्यालयाचा पत्ता')),
                ('office_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='कार्यालयाचा ई-मेल')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='कार्यालयाचा फोन नंबर')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='जिल्हा')),
                ('division_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='विभागाचे नांव')),
                ('divisional_office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='विभागीय कार्यालयाचे नांव')),
                ('divisional_office_address', models.TextField(blank=True, null=True, verbose_name='विभागीय कार्यालयाचा पत्ता')),
                ('designation_01', models.CharField(blank=True, max_length=255, null=True, verbose_name='पदनाम 01')),
                ('designation_02', models.CharField(blank=True, max_length=255, null=True, verbose_name='पदनाम 02')),
                ('working_officer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='कार्यरत अधिका-यांचे नांव')),
                ('administrative_officer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='प्रशासकिय अधिकारी यांचे नांव')),
                ('senior_clerk_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='वरिष्ठ लिपीकांचे नांव')),
                ('junior_clerk_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='कनिष्ठ लिपीकांचे नांव')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'कार्यालयाची माहिती',
                'verbose_name_plural': 'कार्यालयाची माहिती',
                'ordering': ['-created_at'],
            },
        ),
    ]
