# Generated by Django 6.0.3 on 2026-04-18 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_officeinformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(blank=True, choices=[('FIRST', 'मुद्रांक शुल्य वसुली नोटीस'), ('SECOND', 'दुसरी नोटीस'), ('HEARING', 'सुनावणी नोटीस'), ('CASE_FILING', 'बोजा दाखल नोटीस')], max_length=20, null=True, verbose_name='नोटीस प्रकार')),
                ('letter_type', models.CharField(blank=True, choices=[('FULL_PAYMENT', 'पूर्ण रक्कम भरल्यानंतर पत्र'), ('PARTIAL_PAYMENT', 'कमी रक्कम भरल्यानंतर पत्र')], max_length=20, null=True, verbose_name='पत्र प्रकार')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='पाठवलेली दिनांक')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='notices/word/', verbose_name='Word फाइल')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='जनरेट केले आहे')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='inspection.inspectionmemo', verbose_name='तपासणी मेमो')),
            ],
            options={
                'verbose_name': 'नोटीस ट्रॅकिंग',
                'verbose_name_plural': 'नोटीस ट्रॅकिंग',
                'ordering': ['-sent_date'],
            },
        ),
    ]
