# Generated by Django 6.0.3 on 2026-04-18 07:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_noticetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmemo',
            name='balance_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='शिल्लक शास्ती'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='balance_reg_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='शिल्लक नों.फी'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='balance_stamp_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='शिल्लक मु.शु'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='वसूल शास्ती'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_penalty_challan',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='वसुल शास्ती चलन डिफेस क्रं.'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_penalty_date',
            field=models.DateField(blank=True, null=True, verbose_name='वसुली शास्ती चा दिनांक'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_reg_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='वसूल नों.फी'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_reg_fee_challan',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='वसूल नों.फी चलन डिफेस क्रं.'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_reg_fee_date',
            field=models.DateField(blank=True, null=True, verbose_name='वसुली नों.फी चा दिनांक'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_stamp_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='वसुल मु.शु'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_stamp_duty_challan',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='वसुल मु.शु. चलन डिफेस क्रं.'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='recovered_stamp_duty_date',
            field=models.DateField(blank=True, null=True, verbose_name='वसुली मु.शु.चा दिनांक'),
        ),
        migrations.AlterField(
            model_name='inspectionmemo',
            name='recovery_date',
            field=models.DateField(blank=True, null=True, verbose_name='वसुलीचा दिनांक'),
        ),
    ]
