# Generated by Django 6.0.3 on 2026-04-18 07:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_inspectionmemo_balance_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmemo',
            name='penalty_date',
            field=models.DateField(blank=True, null=True, verbose_name='शास्तीचा दिनांक'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.02'), max_digits=5, verbose_name='शास्तीचा दर'),
        ),
    ]
