# Generated by Django 6.0.3 on 2026-04-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_inspectionmemo_penalty_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmemo',
            name='court_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='न्यायालयाचे नाव'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='petition_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='पिटीशन क्रमांक'),
        ),
    ]
