# Generated by Django 6.0.3 on 2026-04-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_inspectionmemo_court_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='शास्तीचा दर')),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='दर मूल्य')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'शास्तीचा दर',
                'verbose_name_plural': 'शास्तीचा दर',
                'ordering': ['rate_value'],
            },
        ),
    ]
