# Generated by Django 6.0.3 on 2026-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_penaltyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmemo',
            name='built_up_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='बांधीव क्षेत्र'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='executant_address',
            field=models.TextField(blank=True, default='', verbose_name='निष्पादकाचा संपुर्ण पत्ता'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='executant_mobile',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='निष्पादकाचा मोबाईल नंबर'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='sold_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='विक्री केलेले क्षेत्र'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='valuation_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='मुल्याकंनातील फरक'),
        ),
        migrations.AlterField(
            model_name='inspectionmemo',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='एकुण क्षेत्रफळ'),
        ),
    ]
