# Generated by Django 6.0.3 on 2026-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_inspectionmemo_built_up_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmemo',
            name='objection_description',
            field=models.TextField(blank=True, default='', verbose_name='आक्षेपाचे थोडक्यात वर्णन'),
        ),
        migrations.AddField(
            model_name='inspectionmemo',
            name='property_income_description',
            field=models.TextField(blank=True, default='', verbose_name='मिळकतीचे थोडक्यात वर्णन'),
        ),
    ]
