# Generated by Django 6.0.3 on 2026-04-18 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_inspectionmemo_objection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticetracking',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='इश्यु दिनांक'),
        ),
        migrations.AddField(
            model_name='noticetracking',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'तयार झाले'), ('SENT', 'पाठविले'), ('CLOSED', 'बंद')], default='GENERATED', max_length=20, verbose_name='स्थिती'),
        ),
    ]
