# Generated by Django 6.0.3 on 2026-04-18 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_noticetracking_issue_date_noticetracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticetracking',
            name='issue_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='इश्यु दिनांक'),
        ),
    ]
