# Generated by Django 6.0.3 on 2026-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_alter_noticetracking_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmemo',
            name='survey_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='गट/सं.नं.क्रमांक'),
        ),
    ]
