# Generated by Django 6.0.3 on 2026-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_inspectionmemo_survey_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmemo',
            name='paragraph_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='परिच्छेद क्र'),
        ),
        migrations.AlterField(
            model_name='noticetracking',
            name='notice_type',
            field=models.CharField(blank=True, choices=[('FIRST', 'प्रथम नोटीस'), ('SECOND', 'दुसरी नोटीस'), ('HEARING', 'सुनावणी नोटीस'), ('CASE_FILING', 'बोजा नोटीस')], max_length=20, null=True, verbose_name='नोटीस प्रकार'),
        ),
    ]
